Use `prop-tests` for prop testing
p2panda/p2panda pull request #188
Opened 2022-01-13 17:54 UTC by sandreae

Use `prop-tests` for prop testing.

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa)

2022-02-22 22:59 UTC, adzialocha approved these changes
Cool. Looking forward to use this more in other tests.

And: Why did noone comment on my secret PR re-naming mission? 😎

2022-02-22 23:35 UTC, sandreae commented
> And: Why did noone comment on my secret PR re-naming mission? sunglasses

Hahahah, I forgot to comment!! When I first saw it, I thought that's what I actually named the PR, took me a while t realise what had been gooooing on. :rofl: :rofl:

2022-03-09 13:39 UTC, cafca requested changes
I have overlooked this PR for too long even when it's actually really really nice. I think a short comment on what `prop_tests.rs` is could be nice in that file.

2022-03-09 13:39 UTC, cafca commented on p2panda-rs/src/operation/operation.rs
> -#[derive(Clone, Debug, Eq, PartialEq)]
You removed `Eq` here?

2022-03-09 13:39 UTC, cafca commented on p2panda-rs/src/tests/prop_tests.rs
> +}
A module docstring could be nice for this, just something short about what a prop test is.

2022-03-09 15:10 UTC, cafca commented
Current problem is that the proptests grow too large with arbitrary hashes being generated and new complexity introduced by `Relation` and friends. I am looking for a way to limit the number of arbitrary hashes that are being tested.

2022-06-10 13:35 UTC, sandreae commented
Yeh, I agree. If we find an area where we want to apply it in the future, we can introduce it then.

2022-06-10 13:35 UTC, closed without merging