Add tests for size and signature method of EntrySigned
p2panda/p2panda pull request #197
Opened 2022-02-01 11:31 UTC by cafca

Text coverage showed that some parts of `EntrySigned` were not covered. I added these tests but the signature seems to be broken. We don't use it anywhere.

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa)

2022-02-01 17:40 UTC, adzialocha commented
Very nice! :+1: 

>  I added these tests but the signature seems to be broken. We don't use it anywhere.

Doesn't sound like it was "broken", but I guess the pending issue related to "it was not used" is here: https://github.com/p2panda/p2panda/issues/35

2022-02-02 12:30 UTC, sandreae commented
> Thanks @sandreae for getting this to work!

Team effort :star:

2022-02-02 15:34 UTC, adzialocha requested changes
Changelog is missing, otherwise alles nice!

2022-02-02 16:19 UTC, adzialocha approved these changes

2022-02-02 16:19 UTC, merged