Some additions to mock node
p2panda/p2panda pull request #219
Opened 2022-02-16 13:26 UTC by sandreae

Describe your changes here.

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa)

2022-02-17 10:30 UTC, sandreae commented
Yeh, that's a good point. For now though, rather than splitting off, I might prefer to implement all the mermaid-js stuff directly in `panda-playground` instead of here in `test_utils`. That would mean the only addition here is a few methods on the mock node. Not against splitting it out, would want to think more about it though.

2022-03-14 13:37 UTC, cafca approved these changes

2022-03-14 13:37 UTC, cafca commented on p2panda-rs/src/test_utils/mocks/node.rs
> +    pub fn replicate_with(&mut self, other_node: &mut Node) -> Vec<Hash> {
Could be nice to have examples for mock node methods. I know they are also in the tests so not required, just - nice to have :-)

2022-03-14 13:38 UTC, cafca requested changes
Actually :D It would be nice to cover all new lines with tests, I think not much is needed for that.

2022-04-18 14:23 UTC, sandreae commented
I'm gunna close this as most of the functionality was moved out into the playground, and soon we will do a revamp of the mock node in any case. This can be approach then if it's still needed.

2022-04-18 14:23 UTC, closed without merging