Split up operation.rs
p2panda/p2panda pull request #232
Opened 2022-02-25 14:52 UTC by cafca

Move everything related to operation fields into a new file `operation_fields.rs`

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
~~- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa) ~~

2022-02-25 15:13 UTC, cafca commented
No codecov? 🤔

2022-02-25 16:38 UTC, adzialocha requested changes
Thank you!!

Minor request: No `println` please!

2022-02-25 17:44 UTC, cafca commented on p2panda-rs/src/operation/operation_fields.rs
> +        println!("{:?}", fields);
🙀🙀🙀

2022-02-26 11:21 UTC, adzialocha approved these changes

2022-02-26 11:26 UTC, merged