Enhancements to schema module
p2panda/p2panda pull request #233
Opened 2022-02-25 14:59 UTC by cafca

- [x] `validate_schema` function
  - moves cddl validation function from module root into new `validation.rs` where other schema validation related functionality will also go in the future
  - add missing tests for this function
  - doesn't panic anymore for invalid cddl definitions
- [x] `SchemaId` 
  - Remove `Deref` implementation 
- [x] `SchemaView` and `SchemaFieldView`
  -  Remove `TooManyFields` error because duplicate fields should be the concern of CDDL
  -  Remove `TooFewFields` error because each field has its own validation anyway which would be more helpful if it comes to a missing field
- [x] Introduce `schema::system` module for implementations of system schemas
- [x] Move definition of `RelationList` next to `Relation` struct
- [x] Add and extend documentation in general

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header
- Check if descriptions and terminology match `handbook` content (and visa-versa) 
  - does not apply

2022-02-25 16:36 UTC, adzialocha approved these changes
Nice refactoring going on!

Two small things, otherwise it looks great:

* I've added a entry to the CHANGELOG since every PR needs one (except of if its literally just removing a character from a comment or something). Yours is actually doing quite many different things, maybe you have a more precise summary for it than I :cat: 
* Added dots to the docstrings for consistency.

2022-02-26 11:56 UTC, sandreae requested changes
Mainly just one question about changing the validation for `SchemaView` and `SchemaFieldView`, otherwise really nice enhancements :+1: thanks!

2022-02-26 11:56 UTC, sandreae commented on p2panda-rs/src/operation/operation_fields.rs
> +pub type RelationList = Vec<Relation>;
Nice to have an own definition for `RelationList` I think i already needed this in a few other places.

2022-02-26 12:14 UTC, sandreae commented on p2panda-rs/src/schema/system/schema.rs
> -
Yep, that would do it.

If it's too few fields, that would be caught later as well, so really it's just too many which is important here.

2022-02-28 14:44 UTC, cafca commented on p2panda-rs/src/schema/system/schema.rs
> -
Ah, I didn't expect any harm from something like that `animals` field in your example. Is that something we need to prevent?

2022-02-28 14:52 UTC, cafca commented
> Nice refactoring going on!
> 
> Two small things, otherwise it looks great:
> 
>     * I've added a entry to the CHANGELOG since every PR needs one (except of if its literally just removing one character from a comment or something). Yours is actually doing quite many different things, maybe you have a more precise summary for it than I 🐱
> 
>     * Added dots to the docstrings for consistency.

Usually I would always add to the changelog, I didn't do that here because these are mostly leftovers from my review of the original review of `SchemaView` and `SchemaFieldView` (and then some other things). I didn't want to make no-changelog-prs a things :)

2022-02-28 14:53 UTC, sandreae commented on p2panda-rs/src/schema/system/schema.rs
> -
Hmm, I feel we should catch cases where we try to parse a document view with invalid fields into a `SchemaView`

2022-02-28 14:54 UTC, adzialocha commented
> Usually I would always add to the changelog, I didn't do that here because these are mostly leftovers from my review of the original review of SchemaView and SchemaFieldView (and then some other things). I didn't want to make no-changelog-prs a things :)

Hmn, I still see your changes as something quite significant though regardless of it it was meant to be as an review or not (some things are even quite nice outside of Sams PR). But I'm happy to discuss where the border is between making a CHANGELOG entry or not.

2022-02-28 15:12 UTC, cafca commented on p2panda-rs/src/schema/system/schema.rs
> -
We can also leave it in, I don't feel so strongly about this, it's just a little bit more complexity that could also be avoided in my opinion (additional check in this implementation + a test needed for that + an additional error type). 

This `TryFrom` implementation will not yield an invalid `SchemaView` instance even when provided with a document view that has this `animals` field, as only the three required fields are kept in the return value (lines 149-154). I can't really see a situation where you'd be helped with this additional check. 

Would you still prefer we keep the check? Then I add it back in and we can move forward :)

2022-02-28 15:23 UTC, adzialocha commented on p2panda-rs/src/schema/system/schema.rs
> -
It could move into a `Validate` trait implementation?

2022-02-28 21:36 UTC, sandreae commented on p2panda-rs/src/schema/system/schema.rs
> -
Hmmm, yeh, I don't wanna hold this up, so let's merge and I will raise an issue :+1:

I definitely wanna chat about it more though as I just can't see how this is desirable behaviour, but maybe that means I'm just misunderstanding the context or something.

2022-02-28 21:37 UTC, sandreae approved these changes

2022-03-01 12:11 UTC, adzialocha commented on p2panda-rs/src/schema/system/schema.rs
> -
I think it is an important point! Please make an issue for it :+1:

2022-03-01 12:11 UTC, merged