Automock
p2panda/p2panda pull request #314
Opened 2022-05-06 08:27 UTC by pietgeursen

I'd really like to be able to write tests that mock the `EntryStore` trait so that my tests don't have to hit a db.
How would you feel about this?

## 📋 Checklist

- [x] Add tests that cover your changes
- [x] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [x] Link this PR to any issues it closes
- [x] New files contain a SPDX license header
- [x] Check if descriptions and terminology match `handbook` content (and visa-versa)

2022-05-06 09:04 UTC, adzialocha commented
> How would you feel about this?

Thats super! Good idea!

Do you mind adding an entry to the `CHANGELOG.md`? We're doing that for every PR. Thank you!!

2022-05-06 09:08 UTC, adzialocha requested changes
Thats super! Good idea!

I only have some panda-police nitpicks. Also, do you mind adding an entry to the `CHANGELOG.md`? You can see how we do it in the document and we're doing that for every PR.

Thank you!!

2022-05-06 09:08 UTC, adzialocha commented on p2panda-rs/Cargo.toml
> +mockall = "0.11.0"
I guess this can not be added in dev dependencies? Makes sense!

2022-05-06 09:08 UTC, adzialocha commented on p2panda-rs/src/storage_provider/traits/entry_store.rs
> +use mockall::automock;
I've been planning to make a simple style guide for our codebase but I haven't done it yet :smile_cat: 

We're fairly strict with how we organize / group imports:

- `std` level imports
- external crate imports
- `crate` level imports
- `super` level imports (only in tests)

2022-05-08 03:24 UTC, sandreae approved these changes
Yeh, fantastic, thanks!

Could this be implemented on all the storage providers? `StorageProvider`, `LogStore` and `EntryStore` all exist in this branch.

2022-05-10 02:50 UTC, pietgeursen commented
> Yeh, fantastic, thanks!
> 
> Could this be implemented on all the storage providers? `StorageProvider`, `LogStore` and `EntryStore` all exist in this branch.

It looks like it's easy to add to `LogStore`.

I _think_ it's impossible to add to `StorageProvider` because we need to be able to mock [multiple inherited traits](https://docs.rs/mockall/0.11.0/mockall/#multiple-and-inherited-traits) as well as [mocking an async trait](https://docs.rs/mockall/0.11.0/mockall/#async-traits). One needs to use the `mock!` macro and the other must use the `#[automock]` attribute.

2022-05-10 02:54 UTC, pietgeursen commented on p2panda-rs/src/storage_provider/traits/log_store.rs
> +    async fn find_document_log_id<'a>(
I need to add this lifetime to keep the compiler happy.

2022-05-10 06:45 UTC, adzialocha approved these changes
✌️✨ First p2panda merge! Yay!

@pietgeursen The clippy CI is sad though, can you see the outputs or do you need more rights?

2022-05-10 07:32 UTC, pietgeursen commented
> The clippy CI is sad though, can you see the outputs or do you need more rights?

I can see the output but it seems to be totally unrelated to my changes.

2022-05-10 07:50 UTC, adzialocha commented
> > The clippy CI is sad though, can you see the outputs or do you need more rights?
> 
> I can see the output but it seems to be totally unrelated to my changes.
> 
> ```
>  error: you are deriving `Hash` but have implemented `PartialEq` explicitly
>   --> src/document/document_view_id.rs:38:17
>    |
> 38 | #[derive(Clone, Hash, Debug, Eq)]
>    |                 ^^^^
>    |
>    = note: `#[deny(clippy::derive_hash_xor_eq)]` on by default
> note: `PartialEq` implemented here
>   --> src/document/document_view_id.rs:87:1
>    |
> 87 | / impl PartialEq for DocumentViewId {
> 88 | |     fn eq(&self, other: &Self) -> bool {
> 89 | |         self.sorted() == other.sorted()
> 90 | |     }
> 91 | | }
>    | |_^
> ```

Ah! This got fixed and merged to main, so we can merge now and all will be good 👍

2022-05-10 07:51 UTC, merged