Rename Author -> PublicKey
p2panda/p2panda pull request #461
Opened 2022-09-03 10:24 UTC by sandreae

Describe your changes here.

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa)

2022-09-03 19:42 UTC, adzialocha requested changes
Thank you for doing this (historic) change 🤩 It looks all good, just have this question and the one above:

It's slightly confusing now that we have two `PublicKey` instances, one coming from the ed25519 crate and the other from us. My suggestion would be: 

1. Wrap the ed25519 struct in ours instead of `String`
2. Return our struct when calling `KeyPair.public_key()`

2022-09-03 19:42 UTC, adzialocha commented on p2panda-rs/src/document/document.rs
> +    pub fn author(&self) -> &PublicKey {
Maybe we should also rename the method to `public_key` (and struct fields etc.)

2022-09-05 09:47 UTC, adzialocha commented on p2panda-rs/src/document/document.rs
> +    pub fn author(&self) -> &PublicKey {
Ah yeah, Author actually makes sense on a document as it could be many public keys

2022-09-06 09:03 UTC, sandreae commented
> Wrap the ed25519 struct in ours instead of String (it's strange anyhow, basically an early sqlx remaining, and we already do this with Signature)

> Return our struct when calling KeyPair.public_key()

Nice, I'll make these changes.

2022-09-06 09:21 UTC, sandreae commented
Hmm, one hitch, `ed25519_dalek` PublicKey doesn't implement `Hash`, soooo I guess we need to manually implement that ourselves on our own `PublicKey` wrapper struct?

2022-09-06 11:05 UTC, adzialocha approved these changes
This looks great!

2022-09-06 11:05 UTC, merged

2022-09-06 11:12 UTC, cafca approved these changes
Looks good! I think we would differentiate information about public keysassociated with a document furthermore anyway dot there would be a key group which is the owner of the document, a public-key who has started the document, and A setof the public keys who have participated in the document in the past, regardless of whether they are members of the key group who is currently owning the document.