Storage trait changes
p2panda/p2panda pull request #469
Opened 2022-12-23 15:34 UTC by sandreae

Part of one of the "code love" NLNet milestones, deals with some left over issues around improving the API of our storage traits. Bulk of the changes were being tracked here: [#149](https://github.com/p2panda/aquadoggo/issues/149)

Looking at these now after some time I spotted one or two implementation decisions which could be improved on, in particular in the `DocumentStore` API which inadvertently introduced a concept of a cache layer, which is not wanted/needed in p2panda-rs. More on that here: #468 .

The general name of the game is: make it simple, less is more, only what we really need.

I want it to be as easy as possible to implement these storage traits for other backends while still satisfying our storage requirements for our core data types `Entry` and `Operation`. 

## Changes
- [ ] remove `StorageLog` struct/trait in favour of passing individual parameters
- [ ] general renaming of badly named methods
- [ ] remove `next_log_id` method which was too smart and has been moved to the `validation` module
- [ ] move remaining top level method to it's store
- [ ] remove `StorageProvider` trait completely (!) in favour of requiring individual storage traits which encourages separation of concerns.
- [ ] remove any concept of "caching" documents and views from `DocumentStore` only leave basic "get" methods which have default trait methods which require `OperationStore` and internally materialise docs each time they're called (inefficient, but no cache!)
- [ ] already introduce `WithId<T>` trait
- [ ] better docs to reflect all this
- [ ] more tests, especially in `DocumentStore` 

closes: #468 ` aquadoggo: [#149](https://github.com/p2panda/aquadoggo/issues/149) [#203](https://github.com/p2panda/aquadoggo/issues/203)

## 📋 Checklist

- [ ] Add tests that cover your changes
- [ ] Add this PR to the _Unreleased_ section in `CHANGELOG.md`
- [ ] Link this PR to any issues it closes
- [ ] New files contain a SPDX license header
- [ ] Check if descriptions and terminology match `handbook` content (and visa-versa)

2023-02-03 16:09 UTC, sandreae commented on p2panda-rs/src/storage_provider/traits/document_store.rs
> +/// Interface for querying `Documents` from the store.
I'm wondering if removing `insert_docment_view` from this store trait was actually a mistake... It is very neat to only have the API outlining the query methods for documents, but now already storage provider implementations will diverge in their expected behaviour. For example, the SQL store in aquadoggo requires an extra materialisation step after insertion of operations, but `MemoryStore` doesn't. 

Realise this is a "future" problem, but makes me wonder if this design decision is right.

2023-02-08 17:11 UTC, adzialocha requested changes
Thank you for this massive rework! Looks and feels like a much better API now without the "optional" materialisation layer.

I mostly have comments on formulations and formatting, love the docstrings! The expressive trait signatures are a little unusual to read, but maybe that's just how it is?

With these small changes + CHANGELOG.md entry I think its good to go!

2023-02-09 09:12 UTC, sandreae commented on p2panda-rs/src/lib.rs
> +/// `WithId<DocumentId>` and `WithId<SchemaId>`.
Yeh, they might have `WithId<OperationId>` and `WithId<SchemaId>`, does that make sense?

2023-02-09 09:16 UTC, sandreae commented on p2panda-rs/src/document/document.rs
> +            Some(WithId::<OperationId>::id(&create_operation).clone().into()),
Yeh, I'm not sure either... I do like it, and don't think it's weird or anything in the world of rust, but is it totally right for us, not sure.... :thinking: shall we leave it "for now"?

2023-02-09 09:17 UTC, sandreae commented on p2panda-rs/src/storage_provider/traits/operation_store.rs
> +/// and one `PublicKey`, they form a mutation graph used to build current or historic `Document` state.
Haha, probably not, I thought it was more generic than "operation graph" but maybe not....

2023-02-09 09:19 UTC, sandreae commented on p2panda-rs/src/document/document.rs
> +            Some(WithId::<OperationId>::id(&create_operation).clone().into()),
I think most of the time the type will be inferred from the calling context.

2023-02-09 11:07 UTC, adzialocha commented on p2panda-rs/src/lib.rs
> +/// `WithId<DocumentId>` and `WithId<SchemaId>`.
Ah okay! Cool.

2023-02-09 11:22 UTC, adzialocha commented
@sandreae, yeessss, one last thing maybe: Think the CHANGELOG can be more descriptive, like, what got changed? Especially as it introduces quite big API changes in this instance (in the future we would do a major release because of such change)

2023-02-09 17:16 UTC, merged